from dataclasses import dataclass
from typing import Set

@dataclass
class MorphemeRule:
    """Represents a morphological rule with its category and meaning."""
    category: str
    meaning: str
    allomorphs: Set[str]

prefix_dict = {
            'răs': MorphemeRule('prefix', 'again/against', {'răs', 'răz'}),
            'în': MorphemeRule('prefix', 'in/into', {'în', 'îm'}),
            'des': MorphemeRule('prefix', 'un/reverse', {'des', 'dez'}),
            'pre': MorphemeRule('prefix', 'pre/before', {'pre'}),
            'ne': MorphemeRule('prefix', 'negation', {'ne'}),
            'sub': MorphemeRule('prefix', 'under', {'sub', 'sup'}),
            'supra': MorphemeRule('prefix', 'above', {'supra'}),
            'ante': MorphemeRule('prefix', 'before', {'ante'}),
            'post': MorphemeRule('prefix', 'after', {'post'}),
            'pseudo': MorphemeRule('prefix', 'fake', {'pseudo'}),
            'sin': MorphemeRule('prefix', 'together', {'sin','sim'}),
            'trans': MorphemeRule('prefix', '1. from a place to another 2. crossing 3. beyond 4. passing through', {'trans'}),
            'tele': MorphemeRule('prefix', 'at a distance', {'tele'}),
            'stră': MorphemeRule('prefix', '1. intensification 2. ancient/old', {'stră'}),
            'super': MorphemeRule('prefix', '1. hierarchically superior 2. relative position 3. quantitative excess 4. qualitatively superior', {'super'}),
            'ace': MorphemeRule('prefix', 'harsh personality characteristics', {'ace'}),
            'aie': MorphemeRule('prefix', 'intense spontaneous process involving significant resources (colloquial)', {'aie'}),
            'neo': MorphemeRule('prefix', 'new', {'neo', 'novo'}),
            'non': MorphemeRule('prefix', 'negation', {'non'}),
            'o': MorphemeRule('prefix', 'opposition', {'o', 'ob'}),
            'olig': MorphemeRule('prefix', 'small amount/quantity', {'olig', 'oligo'}),
            'omni': MorphemeRule('prefix', 'relating to totality, with nuance of diversity', {'omni'}),
            'orto': MorphemeRule('prefix', 'straight/correct', {'orto'}),
            'paleo': MorphemeRule('prefix', 'very old/ancient', {'paleo'}),
            'pan': MorphemeRule('prefix', 'relating to a whole, with nuance of coverage dimension', {'pan'}),
            'pato': MorphemeRule('prefix', 'relating to disease', {'pato'}),
            'per': MorphemeRule('prefix', 'through, with nuance of: intrinsic, essential', {'per'}),
            'peri': MorphemeRule('prefix', '1. proximity 2. around 3. at the edge', {'peri'}),
            'petro': MorphemeRule('prefix', 'relating to petroleum', {'petro'}),
            'iso': MorphemeRule('prefix', 'equality', {'iso', 'izo'}),
            'mega': MorphemeRule('prefix', '1. multiple of 10^6 2. figuratively: very large', {'mega'}),
            'micro': MorphemeRule('prefix', '1. submultiple of 10^-6 of meter 2. very small', {'micro'}),
            'nano': MorphemeRule('prefix', 'submultiple of 10^-9 of meter, equivalent to infra-micro', {'nano'}),
            'ex': MorphemeRule('prefix', 'from inside to outside', {'ex', 'exo', 'extra', 'extro'}),
            'filo': MorphemeRule('prefix', 'lover of something, sympathizer, supporter', {'filo', 'fil'}),
            'fito': MorphemeRule('prefix', 'relating to plants', {'fito', 'phyto'}),
            'fungi': MorphemeRule('prefix', 'relating to fungi', {'fungi', 'mico', 'myco'}),
            'geronto': MorphemeRule('prefix', 'relating to elderly', {'geronto'}),
            'heli': MorphemeRule('prefix', 'relating to helicopters', {'heli'}),
            'helio': MorphemeRule('prefix', 'relating to sun', {'helio'}),
            'hemi': MorphemeRule('prefix', 'half', {'hemi', 'semi', 'emi'}),
            'hemo': MorphemeRule('prefix', 'relating to blood', {'hemo'}),
            'hetero': MorphemeRule('prefix', 'different, opposite, complementary', {'hetero', 'etero'}),
            'hidro': MorphemeRule('prefix', 'relating to water', {'hidro'}),
            'higro': MorphemeRule('prefix', 'relating to humidity', {'higro'}),
            'hiper': MorphemeRule('prefix', 'over, beyond, excess', {'hiper'}),
            'hipo': MorphemeRule('prefix', '1. under 2. relating to horses', {'hipo'}),
            'holo': MorphemeRule('prefix', 'whole, total', {'holo'}),
            'homo': MorphemeRule('prefix', 'of the same kind', {'homo', 'omo'}),
            'i': MorphemeRule('prefix', 'negation through violation, contrary', {'i', 'im', 'in'}),
            'intra': MorphemeRule('prefix', 'interior, towards inside', {'im', 'in', 'intra', 'intro'}),
            'infra': MorphemeRule('prefix', 'under, less than', {'infra'}),
            'inter': MorphemeRule('prefix', '1. situated between two entities in time or space 2. with multiple entities 3. relating to connections 4. relating to relationships between entities', {'inter', 'între'}),
            'centri': MorphemeRule('prefix', 'positioning, relation', {'centri'}),
            'circum': MorphemeRule('prefix', 'referring to a circle', {'circum'}),
            'co': MorphemeRule('prefix', 'together', {'co', 'con'}),
            'contra': MorphemeRule('prefix', '1. opposition 2. correspondence 3. illicit activity 4. adjacent but different', {'contra'}),
            'crono': MorphemeRule('prefix', 'relating to time', {'crono'}),
            'cvasi': MorphemeRule('prefix', 'approximately', {'cvasi'}),
            'de': MorphemeRule('prefix', '1. cancellation, separation 2. intrinsically negative 3. separation 4. definition', {'de', 'dis'}),
            'demo': MorphemeRule('prefix', 'relating to population', {'demo'}),
            'dia': MorphemeRule('prefix', 'passing through', {'dia'}),
            'echi': MorphemeRule('prefix', 'equality between components', {'echi'}),
            'em': MorphemeRule('prefix', 'referring to and determining for an important ensemble', {'em', 'en'}),
            'endo': MorphemeRule('prefix', 'internal, interior', {'endo'}),
            'entero': MorphemeRule('prefix', 'internal, interior', {'entero'}),
            'entomo': MorphemeRule('prefix', 'relating to insects', {'entomo'}),
            'exo': MorphemeRule('prefix', 'external, exterior', {'exo'}),
            'epi': MorphemeRule('prefix', 'over, above', {'epi'}),
            'eso': MorphemeRule('prefix', 'towards interior', {'eso'}),
            'eu': MorphemeRule('prefix', '1. something good 2. relating to European Union', {'eu', 'eur'}),
            'ab': MorphemeRule('prefix', '1. renunciation 2. absorption', {'ab'}),
            'abs': MorphemeRule('prefix', 'extraction', {'abs'}),
            'ad': MorphemeRule('prefix', 'addition', {'ad'}),
            'alo': MorphemeRule('prefix', 'different', {'alo', 'allo'}),
            'am': MorphemeRule('prefix', 'confers importance', {'am'}),
            'ambi': MorphemeRule('prefix', 'both', {'ambi'}),
            'ante': MorphemeRule('prefix', 'before (in time or space)', {'ante', 'avan', 'avant'}),
            'anti': MorphemeRule('prefix', 'against', {'anti'}),
            'anto': MorphemeRule('prefix', 'change', {'anto'}),
            'antre': MorphemeRule('prefix', 'confers importance, method', {'antre'}),
            'antropo': MorphemeRule('prefix', 'relating to human', {'antropo'}),
            'arhi': MorphemeRule('prefix', 'maximum, in noble and clerical hierarchy', {'arhi'}),
            'auto': MorphemeRule('prefix', '1. relating to auto transport 2. automatic 3. independence 4. reflexivity', {'auto'}),
            'bio': MorphemeRule('prefix', 'relating to biological processes', {'bio'}),
            'proto': MorphemeRule('prefix', 'first in a series, rudimentary', {'proto'}),
            'a': MorphemeRule('prefix', '1. negation 2. affinity 3. appearance', {'a', 'an'})
        }

noun_suffix_dict = {
            'tor': MorphemeRule('suffix', 'agent', {'tor', 'toare'}),
            'ție': MorphemeRule('suffix', 'action/result', {'ție', 'ții'}),
            'ime': MorphemeRule('suffix', 'collective', {'ime'}),
            'iță': MorphemeRule('suffix', 'diminutive', {'iță'}),
            'tură': MorphemeRule('suffix', 'action result', {'tură'}),
            're': MorphemeRule('suffix', 'action result, long infinitive', {'re'}),
            'ie':MorphemeRule('suffix', 'action result', {'ie, iune'}),
            'ar':MorphemeRule('suffix', 'action taker/object of action', {'ar, ară'}),
            'abil': MorphemeRule('suffix', 'capable and available to do something', {'abil', 'ibil', 'ubil'}),
            'abilitate': MorphemeRule('suffix', 'capacity and availability to do something', {'abilitate', 'ibilitate', 'ubilitate'}),
            'ace': MorphemeRule('suffix', 'harsh personality characteristics', {'ace'}),
            'aie': MorphemeRule('suffix', 'intense spontaneous process', {'aie'}),
            'al': MorphemeRule('suffix', 'typological, functional or qualitative categorization', {'al', 'ţial', 'ţional'}),
            'an': MorphemeRule('suffix', '1. occupational, positional or behavioral characterization 2. geographical origin', {'an', 'ean', 'ian'}),
            'andru': MorphemeRule('suffix', 'something strong, masculine', {'andru'}),
            'ant': MorphemeRule('suffix', '1. influential, exercising action or activity 2. socially established, agreed, accepted, imposed', {'ant', 'ent', 'ànt', 'ènt'}),
            'are': MorphemeRule('suffix', 'performing an activity, action, process, and often their immediate result', {'are', 'ere', 'ire'}),
            'arh': MorphemeRule('suffix', 'occupant of first position in ordered structure', {'arh'}),
            'arhie': MorphemeRule('suffix', 'hierarchical structure', {'arhie'}),
            'at': MorphemeRule('suffix', '1. exercise or restriction of activities, attributions, liberties, competencies 2. institutionalization', {'at', 'et', 'it', 'ut'}),
            'atru': MorphemeRule('suffix', 'relating to medicine, healing', {'atru'}),
            'autica': MorphemeRule('suffix', 'navigation in specific environments', {'autica', 'eutica'}),
            'aza': MorphemeRule('suffix', 'state, concept, process or defining characterization, broad generality, or perennial', {'aza', 'eza', 'iza'}),
            'cefal': MorphemeRule('suffix', 'relating to hierarchy and power', {'cefal', 'crat', 'cratie'}),
            'ces': MorphemeRule('suffix', 'something that modifies the usual course of things', {'ces'}),
            'cid': MorphemeRule('suffix', 'killer', {'cid'}),
            'lit': MorphemeRule('suffix', 'characteristic of structural diversity', {'lit', 'clit'}),
            'cron': MorphemeRule('suffix', 'relating to time', {'cron'}),
            'gen': MorphemeRule('suffix', 'causes certain consequences', {'gen'}),
            'bil': MorphemeRule('suffix', 'quality, defect', {'bil', 'ace'}),
            'tate': MorphemeRule('suffix', 'ability to achieve quality / create defect', {'abilitate', 'ibilitate', 'tate'})
        }

"""
Morpheme dictionaries are in great part based on Marius Duma's work, cited below. Translation and organization by me.

Duma, M. (2007). Ghid explicativ: Prefixele şi sufixele limbii române. În sprijinul practicării corecte a limbii române actuale. București, România.\
Licensed under CC BY 3.0.
"""